### ISSUE TITLE
How do package.json and process.json work?

### ISSUE THREAD

**Issue by cesarvarela** [Azure-App-Service/node#10]
For the start command, which one is used? There is some precedence?

**Comment by lostintangent** [comment]
@naziml Are there any plans to add support for looking for a start script in the package.json file as well? It would be ideal to have that behavior, to alleviate the need to set the startup file as an App Service setting.

**Comment by fiveisprime** [comment]
👍 to what @lostintangent said. Checking `main` and `scripts.start` from package.json would cover most cases.

**Comment by fiveisprime** [comment]
Is there any reason this logic isn't included in the image?

I noticed that the Ruby image offloads some things to a [startup.sh](https://github.com/Azure-App-Service/ruby/blob/master/2.3-1/startup.sh) script. This same kind of thing could be done here to determine the correct start file, exec args (i.e. experimental flags passed to the node bin parsed from env vars), or even to detect the start file.

```sh
PACKAGE_PATH=/home/site/wwwroot/package.json # Needs a recursive find instead.
MAIN=$(node -pe "require('$PACKAGE_PATH').main || ''" 2> /dev/null || true)
START=$(node -pe "require('$PACKAGE_PATH').scripts.start || ''" 2> /dev/null || true)

# Fall back to testing for local files.
# ...
```

There's a lot of potential here. :)

**Comment by nickwalkmsft** [comment]
Support for detecting scripts.start and running `npm start` has been added. Closing this, although it won't be deployed to production for a while.
