### ISSUE TITLE
node/6.9.3-1/sshd_config RhostsAuthentication

### ISSUE THREAD

**Issue by Song2017** [Azure-App-Service/node#15]
Hi,
node/6.9.3-1/sshd_config RhostsAuthentication looks like not a must.
when I comments it, docker image run successfully without warning '/etc/ssh/sshd_config line 15: Deprecated option RhostsAuthentication'.
I wonder to know if it led to a potential hazard with comment.
Thanks

**Comment by naziml** [comment]
I have fixed this in the develop branch and on next integrate unnecessary options should be gone. Thanks for pointing this out!
