### ISSUE TITLE
Node.js versions

### ISSUE THREAD

**Issue by js-kyle** [Azure-App-Service/node#46]
Hi there - hoping this is the correct place for this question.

I am looking to upgrade some App Services to use the recently released Node.js version which patches for security vulnerabilities https://nodejs.org/en/blog/release/v6.14.3/

Are there plans to add this to the list of available versions in App Service - or is it best to add this version to my own apps manually?

If not - are PR's accepted for new versions, and how long would they take to be available on App Service?

Thank you.

**Comment by tony-gutierrez** [comment]
Also any word on when anything > 8.9.4 will make it to app services?

**Comment by js-kyle** [comment]
@tony-gutierrez I'm not sure this repo is monitored - do you know any other ways to engage the App Service team?

**Comment by tony-gutierrez** [comment]
@rramachand21 @patricklee2 @lostintangent ?

**Comment by patricklee2** [comment]
@tony-gutierrez node 8.11.2 will be available soon

**Comment by tony-gutierrez** [comment]
Anything in the 10. range? What is the process? Just making sure it plays nicely with iisnode?

**Comment by patricklee2** [comment]
10.1.0 will be available soon as well

**Comment by js-kyle** [comment]
Hey @patricklee2 Not sure if you have seen my original post here, but:

I am looking to upgrade some App Services to use the recently released Node.js version `6.14.3` which patches recent security vulnerabilities https://nodejs.org/en/blog/release/v6.14.3/

Are there plans to add this version to the list of available versions in App Service - or is it best to add this version to my own apps manually? Is that even possible with how App Service works? Thanks!

**Comment by patricklee2** [comment]
@ahmedelnably @Jen7714 do we have plans for adding node 6.14.3?

We are using https://feedback.azure.com/forums/169385-web-apps for customer requests.

**Comment by tony-gutierrez** [comment]
Any updates a month later? Node 10??

**Comment by patricklee2** [comment]
done
