### ISSUE TITLE
[Discussion] Remove pre-LTS v6 containers

### ISSUE THREAD

**Issue by lostintangent** [Azure-App-Service/node#7]
In order to help reduce some of the clutter when selecting a runtime stack in the portal (see image below), and encourage the use of Node v6 runtimes that are actually part of the LTS stream (v6.9.*), could we remove the `6.2.2` and `6.6.0` containers, and simply provide Node v6 LTS images?

![image](https://cloud.githubusercontent.com/assets/116461/23527679/c75e03bc-ff4b-11e6-9c03-1e509c254cc9.png)

**Comment by lostintangent** [comment]
@naziml CC for visibility

**Comment by naziml** [comment]
yes, we will do an update and remove a bunch of these in a month or so and add newer ones.

**Comment by lostintangent** [comment]
I'm going to close this since @nickwalkmsft's latest PR just cleaned up the base images, which is awesome!
